version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  test_and_package_microservices:
    jobs:
      build:
        machine: true
        steps:
          - checkout
          #  TEST & PACKAGE BOOKMICROSERVICE
          - run: cd ./BackEnd/bookmicroservice/ && ./mvnw package
          - run: cd ./BackEnd/bookmicroservice/ && ./mvnw test
    #      - run: docker build -t septteam3/bookmicroservice ./BackEnd/bookmicroservice/
          #  TEST & PACKAGE AUTHMICROSERVICE
          - run: cd ./BackEnd/authmicroservice/ && ./mvnw package
          - run: cd ./BackEnd/authmicroservice/ && ./mvnw test
    #      - run: docker build -t septteam3/authmicroservice ./BackEnd/authmicroservice/
          # TEST & BUILD BOOKEROO (REACT)
    #      - run: docker build -t septteam3/bookeroo ./FrontEnd/bookeroo/
  build_and_push_bookmicroservice_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 640476304076.dkr.ecr.ap-southeast-2.amazonaws.com
          aws-access-key-id: AKIAZKH242LGO7FIEOO6
          aws-secret-access-key: 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
          create-repo: true
          dockerfile: Dockerfile
          path: ./BackEnd/bookmicroservice/
          region: ap-southeast-2
          repo: bookmicroservice
          tag: "$CIRCLE_BUILD_NUM"