version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  test_and_package:
    machine: true
    steps:
      - checkout

      #  TEST & PACKAGE BOOKMICROSERVICE
      - run: cd ./BackEnd/bookmicroservice/ && ./mvnw package
      - run: ls ./BackEnd/bookmicroservice/target/
      - persist_to_workspace:
          root: BackEnd/bookmicroservice
          paths:
            - target/*.jar

      #  TEST & PACKAGE AUTHMICROSERVICE
      - run: cd ./BackEnd/authmicroservice/ && ./mvnw package
      - run: ls ./BackEnd/authmicroservice/target/
      - persist_to_workspace:
          root: BackEnd/authmicroservice
          paths:
            - target/*.jar

      # TEST REACT
      - run: cd./FrontEnd/bookeroo/ && RUN npm ci --only=production
      - run: cd ./FrontEnd/bookeroo/ && npm test -- --watchAll=false

workflows:
  package_build_and_push_images:
    jobs:
      # TEST & PACKAGE MICROSERVICES
      - test_and_package

      # BUILD & PUSH BOOKMICROSERVICE IMAGE
      - aws-ecr/build-and-push-image:
          name: aws-ecr/bookmicroservice
          attach-workspace: true
          workspace-root: ./BackEnd/bookmicroservice/
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./BackEnd/bookmicroservice
          region: AWS_REGION
          repo: bookmicroservice
          tag:
#          tag: "v<< pipeline.number >>"
          requires:
            - test_and_package

      # BUILD AND PUSH AUTHMICROSERVICE IMAGE
      - aws-ecr/build-and-push-image:
          name: aws-ecr/authmicroservice
          attach-workspace: true
          workspace-root: ./BackEnd/authmicroservice/
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./BackEnd/authmicroservice
          region: AWS_REGION
          repo: authmicroservice
          tag:
#          tag: "v<< pipeline.number >>"
          requires:
            - test_and_package

      # BUILD AND PUSH BOOKEROO IMAGE
      - aws-ecr/build-and-push-image:
          name: aws-ecr/bookeroo
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./FrontEnd/bookeroo/
          region: AWS_REGION
          repo: bookeroo
          tag:
#          tag: "v<< pipeline.number >>"
          requires:
            - test_and_package