version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  package:
    machine: true
    steps:
      - checkout
      #  TEST & PACKAGE BOOKMICROSERVICE
      - run: cd ./BackEnd/bookmicroservice/ && ./mvnw package && ls target/
      - run: cd ./BackEnd/bookmicroservice/ && ./mvnw test
      - run: sudo docker build -t septteam3/bookmicroservice:$CIRCLE_BUILD_NUM ./Backend/bookmicroservice/
      #  TEST & PACKAGE AUTHMICROSERVICE
#      - run: cd ./BackEnd/authmicroservice/ && ./mvnw package
#      - run: cd ./BackEnd/authmicroservice/ && ./mvnw test

workflows:
  test_and_package_microservices:
    jobs:
      - build
  build_and_push_bookmicroservice_image:
    jobs:
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          workspace-root: ./Backend/bookmicroservice/
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          extra-build-args: ./Backend/bookmicroservice/
          path: ./BackEnd/bookmicroservice/
          region: AWS_REGION
          repo: bookmicroservice
          tag: "$CIRCLE_BUILD_NUM"
          requires:
            - package