version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: cd ./BackEnd/bookmicroservice/ && ./mvnw package
      - run: docker build -t septteam3/bookmicroservice ./BackEnd/bookmicroservice/
      - run: docker build -t septteam3/bookeroo ./FrontEnd/bookeroo/