version: 2
jobs:
  build:
    machine: true
#    working_directory: ./BackEnd/bookmicroservice/
    steps:
      - checkout
      - run: pwd && ls -al
      - run: cd ./BackEnd/bookmicroservice/ && ./mvnw package
      - run: docker build -t septteam3/bookmicroservice ./BackEnd/bookmicroservice/