# NOT FOR PRODUCTION - ONLY TO BE USED FOR TESTING
# STOP CONTAINER, REMOVE CONTAINER
# IMAGE IS NOT REMOVED - MUST BE DONE MANUALLY IF DESIRED
sudo docker stop loginmicroservice
sudo docker stop loginmicroservice
